/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package payroll;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jilweli
 */
public class AdminPage extends javax.swing.JFrame {
    
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
    
    public AdminPage() {
        initComponents();
        Table1();
    }
    
    public void Table1(){
    
        try{
            String sql="select * from employee";
            conn = DriverManager.getConnection("jdbc:mysql://localhost/payroll","root","");
            pst = conn.prepareStatement(sql);
            rs=(ResultSet) pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) Table1.getModel();
            model.setNumRows(0);
            while(rs.next()){
                Object[] data = {rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)};
                model.addRow(data);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        wage = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        employeeRegNo = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        firstname = new javax.swing.JTextField();
        surname = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        workinghours = new javax.swing.JTextField();
        btnModify = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN  IN PAYROLL SYSTEM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 30, 580, 70);

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FIRST NAME", "LAST NAME", "EMPLOYEE REG_NO", "ADDRESS", "WORKING HOURS", "WAGES"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(380, 140, 710, 470);

        jLabel2.setText("SURNAME:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(180, 200, 70, 30);
        getContentPane().add(wage);
        wage.setBounds(180, 540, 190, 30);

        jLabel3.setText("EMPLOYEE REG NO:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 290, 110, 30);

        jLabel4.setText("ADDRESS:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 360, 70, 30);

        jLabel5.setText("WAGE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 510, 110, 30);

        jLabel6.setText("FIRST NAME:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 130, 90, 30);

        employeeRegNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeRegNoActionPerformed(evt);
            }
        });
        getContentPane().add(employeeRegNo);
        employeeRegNo.setBounds(180, 320, 190, 30);
        getContentPane().add(address);
        address.setBounds(180, 390, 190, 30);
        getContentPane().add(firstname);
        firstname.setBounds(180, 170, 190, 30);
        getContentPane().add(surname);
        surname.setBounds(180, 230, 190, 30);

        jTextField6.setText("jTextField1");
        getContentPane().add(jTextField6);
        jTextField6.setBounds(180, 230, 190, 30);

        jLabel7.setText("WORKING HOURS:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(180, 430, 110, 30);
        getContentPane().add(workinghours);
        workinghours.setBounds(180, 470, 190, 30);

        btnModify.setBackground(new java.awt.Color(255, 255, 51));
        btnModify.setText("MODIFY");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });
        getContentPane().add(btnModify);
        btnModify.setBounds(280, 630, 80, 40);

        btnDelete.setBackground(new java.awt.Color(255, 0, 51));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(370, 630, 100, 40);

        btnAdd.setBackground(new java.awt.Color(0, 204, 0));
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdd);
        btnAdd.setBounds(170, 630, 80, 40);

        setSize(new java.awt.Dimension(1128, 755));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        
        String sql = "INSERT INTO employee(firstname,surname,employeeRegNo,address,workinghours,wage) VALUES (?,?,?,?,?,?)";
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/payroll","root","");
            pst = conn.prepareStatement(sql);
            pst.setString(1,firstname.getText());
            pst.setString(2, surname.getText());
            pst.setString(3, employeeRegNo.getText());
            pst.setString(4, address.getText());
            pst.setString(5, workinghours.getText());
            pst.setString(6, wage.getText());
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Employee added to your system");
            Table1();
            
            
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null,ex);
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void employeeRegNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeRegNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeRegNoActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        String sql = "DELETE FROM employee WHERE employeeRegNo=?";
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/payroll","root","");
            pst = conn.prepareStatement(sql);
            pst.setString(1, employeeRegNo.getText());
            
            pst.execute();
            
            JOptionPane.showMessageDialog(null,"Employee'S informations deleted");
            Table1();
            
            
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        // TODO add your handling code here:
        
        String sql = "UPDATE employee SET firstname=?, surname=?, employeeRegNo=?, address=?, workinghours=?, wage=? where employeeRegNo=?";
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/payroll","root","");
            pst = conn.prepareStatement(sql);
            pst.setString(1,firstname.getText());
            pst.setString(2, surname.getText());
            pst.setString(3, employeeRegNo.getText());
            pst.setString(4, address.getText());
            pst.setString(5, workinghours.getText());
            pst.setString(6, wage.getText());
            pst.setString(7, employeeRegNo.getText());
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Employee informations updated");
            Table1();
            
            
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null,ex);
        }
            
    }//GEN-LAST:event_btnModifyActionPerformed

    private void Table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table1MouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel model=(DefaultTableModel) Table1.getModel();
        int SelectedRowIndex=Table1.getSelectedRow();
        firstname.setText((String) Table1.getValueAt(SelectedRowIndex,0));
        surname.setText((String) Table1.getValueAt(SelectedRowIndex,1));
        employeeRegNo.setText((String) Table1.getValueAt(SelectedRowIndex,2));
        address.setText((String) Table1.getValueAt(SelectedRowIndex,3));
        workinghours.setText((String) Table1.getValueAt(SelectedRowIndex,4));
        wage.setText((String) Table1.getValueAt(SelectedRowIndex,5));
    }//GEN-LAST:event_Table1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table1;
    private javax.swing.JTextField address;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnModify;
    private javax.swing.JTextField employeeRegNo;
    private javax.swing.JTextField firstname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField surname;
    private javax.swing.JTextField wage;
    private javax.swing.JTextField workinghours;
    // End of variables declaration//GEN-END:variables
}
